### ISSUE TITLE
invalid path should return 404

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#133] opened 2015-03-24 23:36 UTC
Error:

> java.util.NoSuchElementException: there are no headers by name "Content-Type" [...]
> at org.takes.misc.VerboseIterator.next(VerboseIterator.java:66)
> at org.takes.rq.RqMultipart.<init>(RqMultipart.java:86)
> at com.nerodesk.TkWrite.act(TkWrite.java:73)
> at org.takes.facets.auth.TsAuth$1.act(TsAuth.java:115)
> at org.takes.http.BkBasic.print(BkBasic.java:89)
> at org.takes.http.BkBasic.accept(BkBasic.java:73)
> at org.takes.http.BkSafe.accept(BkSafe.java:58)
> at org.takes.http.BkParallel$1.run(BkParallel.java:90)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at java.lang.Thread.run(Thread.java:745)

Replication:

> access `http://beta.nerodesk.com/w` or any path on the domain

Browsers tested:

> chrome, firefox, safari

Lets return a 404 or a redirect -- displaying code makes the site less secure.

**Comment by yegor256** [comment] 2015-03-25 00:18
@karato definitely a bug

**Comment by karato** [comment] 2015-03-25 01:38
> @karato definitely a bug

@yegor256 sure, thanks, I added bug tag to it

**Comment by karato** [comment] 2015-03-25 03:36
@longtimeago do this task

**Comment by longtimeago** [comment] 2015-03-25 06:41
@k0r @yegor256 please, decide what exactly do you want to see on such errors? No stacktrace, it's good. So, 404 or redirect? Redirect where?
Looks like this issue is a duplicate of https://github.com/teamed/nerodesk/issues/134

**Comment by ghost** [comment] 2015-03-25 17:30
@longtimeago redirection to the main site.

**Comment by longtimeago** [comment] 2015-03-25 17:47
@yegor256 @k0r well ... in this case user would not understand what's going on at all. Maybe, we should show him some error page, but without stacktrace. What do you think?

**Comment by ghost** [comment] 2015-03-25 17:57
@longtimeago if the user is logged in: redirect with status text "please select files to upload."

**Comment by longtimeago** [comment] 2015-03-25 18:17
@k0r and what if user is not logged in?
What is "status text"?

**Comment by ghost** [comment] 2015-03-25 18:19
@longtimeago redirect to login page then display appropriate status text. what do you think?

**Comment by longtimeago** [comment] 2015-03-25 18:21
@k0r hum ... we don't have any login page in developer's mode (when app starts locally on dev PC)

**Comment by ghost** [comment] 2015-03-25 18:22
@longtimeago yeah, it's the main page currently.

**Comment by longtimeago** [comment] 2015-03-25 18:29
@k0r so, I can propose to redirect to this main page regardless of the users status (logged on or not).
Problem is slightly more complicated. As far as I see, we are getting almost the same exception trying to access the urls:

```
http://localhost:8080/r
```

and 

```
http://localhost:8080/d
```

**Comment by longtimeago** [comment] 2015-03-25 18:39
@k0r All these errors caused by bad request and should be handled the same way - redirect to main page.
I used to rest api, where client actually care about such an error because he construct request by himself and can do something meaningful.
In our case, client is not supposed to construct request by himself, so your proposal make sense. If request is bad - redirect.
Now the tricky part - validate the request before processing, or catch the appropriate exception from `takes` and redirect to the main page.
Anyway, looks like I've got the idea. Please, correct me if I'm wrong.

**Comment by ghost** [comment] 2015-03-25 18:41
@longtimeago was thinking the same thing: 

> validate the request before processing, or catch the appropriate exception from takes and redirect to the main page.

**Comment by longtimeago** [comment] 2015-03-25 18:45
@k0r looks like for now `takes` supports only catching

**Comment by ghost** [comment] 2015-03-25 18:49
@longtimeago I'll reformat the ticket to request `IOException` catching on `r`, `w`, and `d`.

**Comment by longtimeago** [comment] 2015-03-25 18:54
@k0r it's not only on these operations actually. If you call some other url you will see almost the same.
Try, for example
`http://localhost:8080/sg`

```
org.takes.NotFoundException: nothing found
    at org.takes.facets.fork.TsFork.route(TsFork.java:103)
    at org.takes.facets.fallback.TsFallback.route(TsFallback.java:97)
    at org.takes.facets.auth.TsAuth$1.act(TsAuth.java:115)
    at org.takes.http.BkBasic.print(BkBasic.java:89)
    at org.takes.http.BkBasic.accept(BkBasic.java:73)
    at org.takes.http.BkSafe.accept(BkSafe.java:58)
    at org.takes.http.BkParallel$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ghost** [comment] 2015-03-25 18:57
@longtimeago ah, yeah. @yegor256 would probably want separate tickets for each catch implementation.

**Comment by longtimeago** [comment] 2015-03-25 18:58
@k0r I don't think so. Handling is the same. We need common approach

**Comment by ghost** [comment] 2015-03-25 19:04
@longtimeago yeah, let's see what @yegor256 says -- [#94](https://github.com/teamed/nerodesk/issues/94), [#137](https://github.com/teamed/nerodesk/issues/137), and [#138](https://github.com/teamed/nerodesk/issues/138) are requesting catch implementation.

**Comment by longtimeago** [comment] 2015-03-25 21:24
see the PR https://github.com/teamed/nerodesk/pull/139

**Comment by yegor256** [comment] 2015-03-26 01:03
@longtimeago I think that this "page not found" problem is very common to all projects, not just this one. I would suggest to add some common component into Takes framework. the solution you proposed in #139 is actually solving two different problems in the same class. It's wrong. Let's deal with them separately. Page not found is one problem, while this "content-type not found" is a completely different story.

**Comment by yegor256** [comment] 2015-03-26 01:03
@longtimeago I would recommend to focus on "content-type not found" problem here and create a separate ticket for "page not found"

**Comment by longtimeago** [comment] 2015-03-26 22:54
@karato please, assign someone else. Really lack of time now, sorry :(

**Comment by ghost** [comment] 2015-03-26 23:22
@yegor256 could you complete this?

**Comment by karato** [comment] 2015-03-27 00:48
> @karato please, assign someone else. Really lack of time now, sorry :(

@longtimeago someone else will help in this task, no problem at all

**Comment by ghost** [comment] 2015-03-27 17:27
@longtimeago this was sorta addressed with 0.3 release. we now get this message `oops, something went wrong!` but code is still displayed and not in the same site font.

**Comment by longtimeago** [comment] 2015-03-27 18:26
@k0r sorry, I can't do the task in time :(
somebody else will take care of it

**Comment by karato** [comment] 2015-04-01 23:13
@carlosmiranda do this task

**Comment by carlosmiranda** [comment] 2015-04-06 04:05
@karato Please assign someone else, too busy at the moment (came from vacation and catching up with pending work).

**Comment by karato** [comment] 2015-04-06 18:24
> @karato Please assign someone else, too busy at the moment (came from vacation and catching up with pending work).

@carlosmiranda got it, someone else will be assigned soon

**Comment by ghost** [comment] 2015-04-06 18:39
@yegor256 let's prioritize this ticket.

**Comment by karato** [comment] 2015-04-06 19:49
@pinaf this is your task

**Comment by pinaf** [comment] 2015-04-07 02:46
@k0r @yegor256 this is what I see when accessing http://beta.nerodesk.com/w
Shall I redirect to home page?

> oops, something went wrong! org.takes.NotFoundException: GET http://beta.nerodesk.com/w at org.takes.tk.TkVerbose$1.act(TkVerbose.java:59) at org.takes.tk.TkWrap.act(TkWrap.java:59) at org.takes.facets.fallback.TkFallback.act(TkFallback.java:70) at org.takes.tk.TkWrap.act(TkWrap.java:59) at org.takes.http.BkBasic.print(BkBasic.java:89) at org.takes.http.BkBasic.accept(BkBasic.java:73) at org.takes.http.BkSafe.accept(BkSafe.java:58) at org.takes.http.BkParallel$1.run(BkParallel.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) Caused by: org.takes.NotFoundException at org.takes.facets.fork.TkFork.act(TkFork.java:103) at org.takes.facets.auth.TkAuth.act(TkAuth.java:91) at org.takes.facets.flash.TkFlash.act(TkFlash.java:104) at org.takes.tk.TkVerbose$1.act(TkVerbose.java:57) ... 10 more

**Comment by ghost** [comment] 2015-04-07 02:48
@pinaf let's redirect to a 404.

**Comment by ghost** [comment] 2015-04-07 02:54
@pinaf updated response.

**Comment by pinaf** [comment] 2015-04-07 02:56
@k0r am I correct in assuming that there is no 404/page not found page yet anywhere in the system?

**Comment by ghost** [comment] 2015-04-07 02:58
@pinaf yeah, this hasn't been implemented yet.

**Comment by pinaf** [comment] 2015-04-07 04:08
@karato please see PR #202

**Comment by pinaf** [comment] 2015-04-09 20:20
@k0r merged :)

**Comment by ghost** [comment] 2015-04-09 20:38
@pinaf thanks.

**Comment by karato** [comment] 2015-04-10 02:51
there is a puzzle in this code `133-6981119b`, we'll resolve it later

**Comment by pinaf** [comment] 2015-04-10 03:02
@k0r please close if alright

**Closed as completed** 2015-04-10 05:11 UTC
Labels: bug, 30 mins, DEV

**Comment by yegor256** [comment] 2015-04-10 22:08
@rultor release, tag is `0.3.10`

**Comment by karato** [comment] 2015-04-13 18:21
@pinaf paid, thanks, added **38 mins** to your account, payment `AP-3SB532806J0487309`, 95 hours and 13 mins was spent

there is a bonus for fast delivery (age=2913)

+38 added to your rating, at the moment it is: [+6626](http://www.netbout.com/b/35128?open=rating)
