### ISSUE TITLE
Remove File Name Field

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#94] opened 2015-03-18 21:09 UTC
Error:

> files uploaded without file name field utilization

Replication:

> upload any file without naming the file using the currently implemented file name field

Browsers tested:

> chrome, firefox, safari

@yegor256 responses:

> the real problem here is that when a user doesn't enter file name we don't say "file name is mandatory". instead, we're passing the request to Amazon S3 and the result is unpredictable.
> we should get rid of that "name" field and use the name of the file from disc.

![file listing bug](http://www.nerodesk.com/nd_file_listing_bug.jpg)

**Comment by yegor256** [comment] 2015-03-18 21:51
@k0r is it reproducible with any file or only this specific one?

**Comment by ghost** [comment] 2015-03-18 21:53
@yegor256 updated.

**Comment by yegor256** [comment] 2015-03-18 22:17
@k0r can you try to upload a smaller file and check whether the bug is still there?

**Comment by ghost** [comment] 2015-03-18 22:22
@yegor256 1mb file uploaded -- no file listing.

**Comment by yegor256** [comment] 2015-03-18 22:28
can you make a screenshot of the web page you see? with no listing.

**Comment by k0r** [comment] 2015-03-18 22:34
@yegor256 emailed.

**Comment by yegor256** [comment] 2015-03-18 22:46
@k0r please attach it here, there is a link below. thanks

**Comment by k0r** [comment] 2015-03-18 22:46
![file listing bug](http://www.nerodesk.com/nd_file_listing_bug.jpg)

**Comment by yegor256** [comment] 2015-03-19 22:30
@k0r what browser are you using?

**Comment by ghost** [comment] 2015-03-20 04:38
@yegor256 updated.

**Comment by yegor256** [comment] 2015-03-20 04:55
@k0r that's weird... can you try a small file? like 100kb

**Comment by ghost** [comment] 2015-03-20 06:27
@yegor256 same result.

**Comment by yegor256** [comment] 2015-03-20 06:31
@k0r it's a magic... ok, let's assign it to one of developers and see what they say

**Comment by yegor256** [comment] 2015-03-20 06:31
@karato it's a bug, dispatch it pls

**Comment by karato** [comment] 2015-03-20 18:02
> @karato it's a bug, dispatch it pls

@yegor256 OK, I labeled it as `bug`

**Comment by karato** [comment] 2015-03-20 19:55
@ggajos this is your task

**Comment by k0r** [comment] 2015-03-20 23:29
@karato ETA?

**Comment by ghost** [comment] 2015-03-21 18:13
I'd recommend @yegor256 to fix this.

**Comment by ggajos** [comment] 2015-03-23 08:05
@karato we're waiting for #127

**Comment by karato** [comment] 2015-03-23 18:03
> @karato we're waiting for #127

@ggajos right, let's wait for #127

**Comment by yegor256** [comment] 2015-03-24 19:20
@ggajos I can confirm that this problem exists, but only in FireFox. This is the request it is sending:

```
Content-Type: multipart/form-data; boundary=---------------------------174460693920145912822008497972
Content-Length: 489930

-----------------------------174460693920145912822008497972
Content-Disposition: form-data; name="name"


-----------------------------174460693920145912822008497972
Content-Disposition: form-data; name="file"; filename="x.png"
Content-Type: image/png

PNG
... skipped...
-----------------------------174460693920145912822008497972
Content-Disposition: form-data; name="upload"

Submit Query
-----------------------------174460693920145912822008497972--
```

**Comment by yegor256** [comment] 2015-03-24 19:20
@ggajos I suspect this problem is related to the one reported in #120

**Comment by yegor256** [comment] 2015-03-25 04:37
@k0r I think I know what's going on. you're not entering the name of the file. you should enter the name of the file into the field AND select the file from the disc. then, click "submit"

**Comment by ghost** [comment] 2015-03-25 04:57
@yegor256 ah, that was it. there isn't any indication that's required though. thanks.

**Comment by yegor256** [comment] 2015-03-25 05:06
@k0r the real bug here is that we should not allow a user to upload a file when its name is not provided. could you please change the description of this issue and its title to reflect this. the real problem here is that when a user doesn't enter file name we don't say "file name is mandatory". instead, we're passing the request to Amazon S3 and the result is unpredictable.

**Comment by ghost** [comment] 2015-03-25 05:08
@yegor256 was thinking the same thing.

**Comment by ghost** [comment] 2015-03-25 05:11
@yegor256 shouldn't file names be based on the file name from the disc the user is uploading from? renaming the file before and after upload should be optional -- auto fill the file name text box with the original file name from the disc, perhaps?

**Comment by ghost** [comment] 2015-03-25 05:20
@yegor256 multiple file selections should be considered as well. doing batch uploads and having to set the file name for each file is somewhat counterproductive.

**Comment by yegor256** [comment] 2015-03-25 05:46
@k0r yes, totally agree, we should get rid of that "name" field and use the name of the file from disc. please, update the description of the ticket again. also, good idea about batch upload, please create a ticket for this

**Comment by ghost** [comment] 2015-03-25 05:53
@yegor256 updated.

**Comment by karato** [comment] 2015-03-25 17:59
#127 is closed, it was an impediment

**Comment by yegor256** [comment] 2015-03-26 01:10
@ggajos I think you can proceed here, the problem is obvious (see above)

**Comment by ggajos** [comment] 2015-03-26 08:46
PR #94

**Comment by karato** [comment] 2015-03-27 21:01
2 puzzles were created here: `94-073592b9`, `94-7efd5d22`

**Comment by karato** [comment] 2015-04-02 17:52
@ggajos 7 days already, in 48 hours I will re-assign. -30 to your rating, your total score is [+3331](http://www.netbout.com/b/35094?open=rating)

**Comment by ghost** [comment] 2015-04-02 19:58
@yegor256 can we close this ticket? file name field seems to have been removed with release tag 0.3.1.

**Comment by yegor256** [comment] 2015-04-02 20:54
@k0r right, it's fixed

**Comment by karato** [comment] 2015-04-02 21:39
@yegor256 please don't close the issue, ask @k0r to do this instead, since he is the author of it

**Closed as completed** 2015-04-02 22:29 UTC
Labels: bug, 30 mins, DEV

**Comment by karato** [comment] 2015-04-03 22:07
@ggajos I just added **38 mins** to your account, many thanks for your contribution.. AP-11C4919338411623V spent here; age=3262, that's why a bonus here for fast delivery; +38 added to your rating, current score is: [+3387](http://www.netbout.com/b/35094?open=rating)

**Comment by karato** [comment] 2015-05-26 01:05
@ghost the last puzzle `94-7efd5d22`/#154 solved
