### ISSUE TITLE
user can't create folders

### ISSUE THREAD

**Issue by ghost** [Nerodesk/nerodesk#150] opened 2015-03-27 17:49 UTC
Current version of README doesn't say anything about file paths or folders for organizing uploaded data. This is a bug, since this feature is important and will improve usability of the system. Let's modify the README and document this feature. Then, let's implement it and test.

**Comment by yegor256** [comment] 2015-03-27 18:27
@k0r could you please alter the description and title like I did in #151

**Comment by k0r** [comment] 2015-03-27 18:30
@yegor256 done.

**Comment by yegor256** [comment] 2015-03-27 18:30
@karato this is definitely a bug, let's dispatch it

**Comment by yegor256** [comment] 2015-03-27 18:41
@k0r thanks, you got the idea :)

**Comment by ghost** [comment] 2015-03-27 18:53
@yegor256 thanks.

**Comment by karato** [comment] 2015-03-27 21:00
> @karato this is definitely a bug, let's dispatch it

@yegor256 sure, thanks, I added bug tag to it

**Comment by karato** [comment] 2015-04-01 03:03
@ggajos this is your task

**Comment by ggajos** [comment] 2015-04-01 15:31
PR #167

**Comment by ggajos** [comment] 2015-04-07 06:50
@karato we might need more time here

**Comment by karato** [comment] 2015-04-07 19:55
> @karato we might need more time here

@ggajos OK, take your time

**Comment by ggajos** [comment] 2015-04-09 06:37
@k0r #167 merged, please close if that's all here, thanks

**Comment by ghost** [comment] 2015-04-09 09:20
@ggajos thanks.

**Comment by karato** [comment] 2015-04-10 02:51
there is a puzzle in this code `150-9049471a`, we'll resolve it later

**Comment by ghost** [comment] 2015-04-10 22:48
after submitting a new directory to create, it redirects to a blank page on the path `/dir/create` with release tag 0.3.10.

**Comment by karato** [comment] 2015-04-12 22:11
@ggajos the project is currently on pause, please stop working with this task until further notice

**Comment by karato** [comment] 2015-04-21 04:07
@ggajos the project is not on pause any more, please continue to work with the task

**Comment by ggajos** [comment] 2015-04-21 10:32
@karato think we're waiting for `150-9049471a`, please correct me if something else has to be done on my side, thanks

**Comment by k0r** [comment] 2015-05-06 19:43
@karato any updates with this task?

**Comment by yegor256** [comment] 2015-05-06 21:07
@karato pls close this ticket

**Comment by k0r** [comment] 2015-05-06 21:09
@yegor256 this hasn't been implemented yet.

**Comment by k0r** [comment] 2015-05-06 21:13
@yegor256 should a ticket requesting the layout to support directories be opened?

**Comment by yegor256** [comment] 2015-05-06 21:17
@k0r we have it already: https://github.com/Nerodesk/nerodesk/issues/221

**Comment by k0r** [comment] 2015-05-06 21:41
@yegor256 thanks.

**Comment by karato** [comment] 2015-05-07 01:20
> @karato pls close this ticket

@yegor256 OK, the issue is closed as requested

**Comment by karato** [comment] 2015-05-08 03:17
@ggajos paid, thanks, added **38 mins** to your account, payment `AP-1B540150B1749624W`, 382 hours and 1 min was spent

the bonus for fast delivery (age=2934)

+38 added to your rating, at the moment it is: [+3066](http://www.netbout.com/b/35094?open=rating)

**Comment by k0r** [comment] 2015-05-22 23:39
@yegor256 not sure why this ticket was closed. submit button for creating a `dir` doesn't do anything.

**Comment by yegor256** [comment] 2015-05-22 23:53
@k0r it doesn't do anything, but it was created. the implementation of folder creation will be done in other tickets, we'll create them later.

**Comment by yegor256** [comment] 2015-05-22 23:53
@karato pls close this issue

**Comment by karato** [comment] 2015-05-25 22:09
> @karato pls close this issue

@yegor256 closing, as asked

**Closed as completed by karato** 2015-05-25 22:09 UTC
Labels: bug, 30 mins, DEV
