### ISSUE TITLE
Large file remains available and truncated

### ISSUE THREAD

**Issue by pinaf** [Nerodesk/nerodesk#276] opened 2015-05-09 00:59 UTC
When uploading a large file, even though the exception page is shown, the file shows up in the file listing when the list page is called again. See exception and screen shot below. Note the large file was truncated to 10Mb.

> oops, something went wrong!
> java.lang.IllegalArgumentException: Now you can't upload a file that is larger than 10000000 bytes

![nerodesk-large-file](https://cloud.githubusercontent.com/assets/1054771/7547912/6ce338be-f5cd-11e4-9f9f-95e825af4967.jpg)

**Comment by k0r** [comment] 2015-05-09 01:04
@pinaf this is a duplicate of #252. copy the ticket description and post it as a comment.

**Comment by pinaf** [comment] 2015-05-09 01:15
@k0r Are you sure you don't want to keep the 2 issues separate (cancelled file and large file)?

**Comment by k0r** [comment] 2015-05-09 01:18
@pinaf it's the same problem. if a file is cancelled or if it exceeds the file limit, the panel contains the file.

**Closed as completed** 2015-05-09 01:32 UTC
