### ISSUE TITLE
AwsDocsTest.listDocs fails

### ISSUE THREAD

**Issue by pinaf** [Nerodesk/nerodesk#159] opened 2015-03-28 01:59 UTC
Taken from https://travis-ci.org/teamed/nerodesk/builds/56177433

> listsDocs(com.nerodesk.om.aws.AwsDocsTest)  Time elapsed: 0.542 sec  <<< FAILURE!
> java.lang.AssertionError: 
> Expected: <[lists-exists, sub/file]>
>      but: was <[sub/file, lists-exists]>
>     at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
>     at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)

The test should either guarantee the order of elements (by sorting) or, instead, check twice for 'contains' instead of checking for equality of the lists.

**Comment by caarlos0** [comment] 2015-03-28 18:10
Valid bug!

I tried to fix it by adding two `contains` matchers, but sometimes it only have one item in the list. I think we may need to change this test.

**Comment by pinaf** [comment] 2015-03-28 18:11
weird.. it should always have both items.

**Comment by longtimeago** [comment] 2015-03-29 16:17
@pinaf the problem is in the order. I have two entries but in the reverse order

**Comment by longtimeago** [comment] 2015-03-29 16:29
@pinaf here is the hotfix https://github.com/teamed/nerodesk/pull/161

**Comment by pinaf** [comment] 2015-03-29 17:43
@longtimeago cool but we need the architect to mark as a bug and the manager to assign I guess :P
@yegor256  ?

**Comment by longtimeago** [comment] 2015-03-29 17:46
@pinaf it's rather small fix. Let's just merge PR and close the issue

**Comment by yegor256** [comment] 2015-03-29 17:52
indeed, the bug is small, thanks for the PR.

**Closed as completed by yegor256** 2015-03-29 17:52 UTC
Labels: invalid

**Comment by pinaf** [comment] 2015-03-29 18:07
@longtimeago I can't merge it...
